### ISSUE TITLE
Could you please upload the whole project file

### ISSUE THREAD

**Issue by codingwatching** [GraesonB/ChatGPT-Wrapper-For-Unity#1]
Hi @GraesonB 
I just found your project and it looks awesome!
Could you please upload the full project so I can get started more easily?
Thank you so much!

**Comment by GraesonB** [comment]
Thank you :-)

I realized that a lot of the files in the repo were doubled up and causing conflicts if it were to be added to a project, so if that was getting in your way I'd redownload the folder. 

I still uploaded the project for you anyways:
https://github.com/GraesonB/ChatGPT-Unity-Wrapper-Demo

Please let me know if you have any other issues getting it working!

**Comment by bea1syv** [comment]
Link no longer available

**Comment by Zukunft39** [comment]
Link no longer available QAQ
