### ISSUE TITLE
Please update docs (add APIKEY usage notes)

### ISSUE THREAD

**Issue by KonH** [GraesonB/ChatGPT-Wrapper-For-Unity#15]
Also, now the API key in the script field not actually working (it got overridden with a resources asset value or nothing works if the asset does not exist because of NRE).  
I think it makes sense to set asset variant optional (if it presents - use it, if it is not present - use field value). Or make API key field non-serializable to prevent confusion.

**Comment by GraesonB** [comment]
Thanks for letting me know, I'll fix it up
