### ISSUE TITLE
Project request, please.

### ISSUE THREAD

**Issue by luckyjoy1001** [GraesonB/ChatGPT-Wrapper-For-Unity#17]
Hi, I love the UI you design. I am trying to make my own chat interface, and the interface you have implemented is very good-looking, can you provide me with a project for reference, thank you very much!

**Comment by GraesonB** [comment]
I’ll upload the project file in another repo after I update this repo, i
might be able to get to it this weekend :-)

**Comment by RicardoMen** [comment]
i want too. Can you share the proyect plz?

**Comment by GraesonB** [comment]
Here it is:
https://github.com/GraesonB/chatgpt-unity-example

Let me know if you have any issues getting it working
