### ISSUE TITLE
How to add the "ChatGPTConversation" script to a game object？

### ISSUE THREAD

**Issue by xiachongyu** [GraesonB/ChatGPT-Wrapper-For-Unity#2]
after click the "add componet ", I cant find the ChatGPTConversation . This is very confusing to me. Thank you!

**Comment by GraesonB** [comment]
If it's not showing up in the  add component dropdown, you could try finding the script in your project window and dragging it onto the game object. If you're still having issues could you screenshot your project window and include it here?
