### ISSUE TITLE
Over requesting tokens in base project.

### ISSUE THREAD

**Issue by janimator0** [GraesonB/ChatGPT-Wrapper-For-Unity#20]
For some reason when running a very basic version of this project my token count is being miscalculated resulting in HTTP Error: HTTP/1.1 400 Bad Request.

It seems that the requested token count is rising based on the given prompts. This is the error: This model's maximum context length is 4097 tokens. However, you requested 4347 tokens (251 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.

My initial message is default and my prompt is essentially "say Hello"

removing **max_tokens** field from **ChatGPTReq** solves the issue

**Comment by GraesonB** [comment]
Thanks, I fixed the default value for max_tokens to something that makes more sense.
