### ISSUE TITLE
Could you please upload your whole project?QAQ

### ISSUE THREAD

**Issue by Zukunft39** [GraesonB/ChatGPT-Wrapper-For-Unity#23]
Hi @GraesonB
Well, your project is pretty goood! But as a beginner, I can't use it successfully.
Could you please upload the full project so I can get started more easily?
Thank you so much!QAQ

**Comment by GraesonB** [comment]
https://github.com/GraesonB/chatgpt-unity-example

This is a bit of a dead project, but you should still be able to get it working. Good luck :-)

**Comment by Zukunft39** [comment]
Oh, thank you so much!🥰Tomorrow i 'd like to have a try, thanks!
