### ISSUE TITLE
Hitting max tokens of 4096

### ISSUE THREAD

**Issue by joeyslucky22** [GraesonB/ChatGPT-Wrapper-For-Unity#8]
I'm not entirely familiar with tokens but after using it for a bit, I'm reaching the max. Is there a way to prevent this?

```
HTTP Error: HTTP/1.1 400 Bad Request
UnityEngine.Debug:LogError (object)
ChatGPTWrapper.Requests/<PostReq>d__2`1<ChatGPTWrapper.ChatGPTRes>:MoveNext () (at Assets/Requests.cs:80)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
```
```
This model's maximum context length is 4096 tokens. However, your messages resulted in 4098 tokens. Please reduce the length of the messages.
UnityEngine.Debug:LogError (object)
ChatGPTWrapper.Requests/<PostReq>d__2`1<ChatGPTWrapper.ChatGPTRes>:MoveNext () (at Assets/Requests.cs:83)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
```

**Comment by GraesonB** [comment]
Unfortunately, the API will cap your conversation at a certain amount of tokens. To be honest, I'm not too sure how tokens are counted, but what it boils down to is the longer the conversation, the more tokens the request will use. The only way around this is by shrinking the previous messages, or removing entire messages before the request is sent. I'll have to work on a solution for this without losing too much context in the conversations.
